### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by hypnopump** [karpathy/covid-sanity#9]
Got 502 Bad Gateway when trying to access project URL

**Comment by karpathy** [comment]
Server crashed, had to restart it manually. I think I understand the error: it was complaining about misformated json, which is probably because I don't use a database but janky json files for the database, and likely the Twitter scraper was writing a json file just as the server was reading it. Will do a quick patch but this is basically a consequence of being cheap and trying to cut corners.

**Comment by karpathy** [comment]
To follow up here: a quick fix for this was merged here a few days ago https://github.com/karpathy/covid-sanity/commit/8ce4543c3457174af8ced432f96b8a92fe47c809  and I haven't seen the issue since.
